default:
  data_raw: "./data/raw/"
  file_amino_acid: "COMFORT_Plasma_Aminoacids_Final.xlsx"
  sheet_amino_acid: "Combined results"
  file_bile_acid: "COMFORT_Faecal_Bileacids_Final.xlsx"
  sheet_bile_acid: "conc ug per g DW"
  file_fmetab: "COMFORT_Faecal_Metabolomics_All_data_Final.xlsx"
  sheet_fmetab_HILIC: "HILIC"
  sheet_fmetab_C18: "C18"
  sheet_fmetab_Lipid: "Lipid"
  file_organic_acid: "Copy of PYC0217_HVN_Healthy Digestion COMFORT faecal SCFAs Sept2020.xlsx"
  sheet_organic_acid: "Collaborator Results Report wet"
  file_pmetab: "COMFORT_Plasma_Metabolomics_All_data_Final.xlsx"
  sheet_pmetab_HILIC: "HILIC All 206 SIMCA"
  sheet_pmetab_C18: "C18 All 206 SIMCA"
  sheet_pmetab_Lipid: "Lipid All 206 SIMCA"
  file_PRO: "Mental Health and symptom data.xlsx"
  file_metagenomics_metadata: "metagenomics/HVN_EG_B1-B4_shotgun_metadata.txt"
  file_metagenomics_taxa: "metagenomics/HVN_EG_B1234_TAXA_SPECIES.txt"
  file_metagenomics_gene_mgseq: "metagenomics/HVN_EG_B1234_KEGG_ALL_LEVELS_mgseq.txt"
  file_metagenomics_gene_heir: "metagenomics/HVN_EG_B1234_KEGG_ALL_LEVELS_hierarchy.txt"
  data_FEA: "./data/processed/metaboanalyst-output/"
  data_mplus: "./data/for_mplus/"
  data_processed: "./data/processed/"
  data_results: "./data/results/"
  data_cluster_assignments: "./data/cluster_assignments/"
  data_consensus_matrices: "./data/consensus_matrices/"
  figures: "./analysis/results/figures/"
  sup_figures: "./analysis/results/sup_figures/"
  tables: "./analysis/results/tables/"