name: hvncluster
channels:
  - bioconda
  - conda-forge
dependencies:
  - _python_abi3_support=1.0
  - _r-mutex=1.0.1
  - appnope=0.1.4
  - argcomplete=3.6.2
  - asttokens=3.0.0
  - babel=2.17.0
  - bioconductor-annotationdbi=1.68.0
  - bioconductor-biobase=2.66.0
  - bioconductor-biocgenerics=0.52.0
  - bioconductor-biocparallel=1.40.0
  - bioconductor-biostrings=2.74.0
  - bioconductor-data-packages=20250625
  - bioconductor-dose=4.0.0
  - bioconductor-enhancedvolcano=1.24.0
  - bioconductor-enrichplot=1.26.1
  - bioconductor-fgsea=1.32.2
  - bioconductor-genomeinfodb=1.42.0
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-ggtree=3.14.0
  - bioconductor-go.db=3.20.0
  - bioconductor-gosemsim=2.32.0
  - bioconductor-iranges=2.40.0
  - bioconductor-keggrest=1.46.0
  - bioconductor-qvalue=2.38.0
  - bioconductor-s4vectors=0.44.0
  - bioconductor-treeio=1.30.0
  - bioconductor-ucsc.utils=1.2.0
  - bioconductor-xvector=0.46.0
  - bioconductor-zlibbioc=1.52.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - cctools_osx-arm64=1024.3
  - cffi=1.17.1
  - clang=20.1.8
  - clang-20=20.1.8
  - clang_impl_osx-arm64=20.1.8
  - clang_osx-arm64=20.1.8
  - clangxx=20.1.8
  - clangxx_impl_osx-arm64=20.1.8
  - clangxx_osx-arm64=20.1.8
  - comm=0.2.3
  - commonmark=0.9.1
  - compiler-rt=20.1.8
  - compiler-rt_osx-arm64=20.1.8
  - contourpy=1.3.3
  - cpython=3.12.11
  - curl=8.14.1
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - faicons=0.2.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freetype=2.13.3
  - fribidi=1.0.10
  - future=1.0.0
  - gfortran_impl_osx-arm64=13.4.0
  - gfortran_osx-arm64=13.4.0
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - great_tables=0.18.0
  - gsl=2.7
  - harfbuzz=11.1.0
  - htmltools=0.6.0
  - icu=75.1
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - isl=0.26
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jq=1.8.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld64_osx-arm64=955.13
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.8
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libcxx-devel=20.1.8
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran-devel_osx-arm64=13.4.0
  - libgfortran5=15.1.0
  - libgit2=1.8.4
  - libglib=2.84.0
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.8
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - llvm-tools=20.1.8
  - llvm-tools-20=20.1.8
  - make=4.4.1
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mpc=1.3.1
  - mpfr=4.2.1
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlopt=2.10.0
  - numpy=2.3.2
  - oniguruma=6.9.10
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.3.2
  - pandoc=3.7.0.2
  - pango=1.56.3
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.3
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.11
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qhull=2020.2
  - r-abind=1.4_8
  - r-anytime=0.3.12
  - r-ape=5.8_1
  - r-aplot=0.2.8
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.4.3
  - r-base64enc=0.1_3
  - r-bayesm=3.1_6
  - r-bh=1.87.0_1
  - r-bigd=0.3.1
  - r-bit=4.6.0
  - r-bit64=4.6.0_1
  - r-bitops=1.0_9
  - r-blob=1.2.4
  - r-boot=1.3_32
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-broom=1.0.9
  - r-bslib=0.9.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-car=3.1_3
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-catools=1.18.3
  - r-cellranger=1.1.0
  - r-class=7.3_23
  - r-cli=3.6.5
  - r-clipr=0.8.0
  - r-clock=0.7.3
  - r-cluster=2.1.8.1
  - r-codetools=0.2_20
  - r-colorspace=2.1_1
  - r-commonmark=2.0.0
  - r-compositions=2.0_9
  - r-config=0.3.2
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-corrplot=0.95
  - r-cowplot=1.2.0
  - r-cpp11=0.5.2
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-crosstalk=1.2.2
  - r-curl=7.0.0
  - r-data.table=1.17.8
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-deoptimr=1.1_4
  - r-deriv=4.2.0
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-dials=1.4.2
  - r-dicedesign=1.10
  - r-diffobj=0.3.6
  - r-digest=0.6.37
  - r-doby=4.7.0
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.5
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fastmatch=1.1_6
  - r-fontawesome=0.5.3
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-forecast=8.24.0
  - r-formatr=1.14
  - r-formula=1.2_5
  - r-fracdiff=1.5_3
  - r-fs=1.6.6
  - r-furrr=0.3.1
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.67.0
  - r-future.apply=1.20.0
  - r-gargle=1.5.2
  - r-gbrd=0.4.12
  - r-generics=0.1.4
  - r-gert=2.1.4
  - r-ggforce=0.5.0
  - r-ggfun=0.2.0
  - r-ggnewscale=0.5.2
  - r-ggplot2=3.5.2
  - r-ggplotify=0.1.2
  - r-ggprism=1.0.7
  - r-ggpubr=0.6.1
  - r-ggrepel=0.9.6
  - r-ggsci=3.2.0
  - r-ggsignif=0.6.4
  - r-ggtangle=0.0.7
  - r-ggthemes=5.1.0
  - r-gh=1.5.0
  - r-gitcreds=0.1.2
  - r-globals=0.18.0
  - r-glue=1.8.0
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gpfit=1.0_9
  - r-gplots=3.2.0
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gt=1.0.0
  - r-gtable=0.3.6
  - r-gtools=3.9.5
  - r-hardhat=1.4.2
  - r-haven=2.5.5
  - r-hexbin=1.28.5
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.16
  - r-httr=1.4.7
  - r-httr2=1.2.1
  - r-ids=1.0.1
  - r-igraph=2.1.4
  - r-infer=1.0.9
  - r-ini=0.3.1
  - r-ipred=0.9_15
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-janitor=2.2.1
  - r-jquerylib=0.1.4
  - r-jsonlite=2.0.0
  - r-juicyjuice=0.1.0
  - r-kernsmooth=2.23_26
  - r-knitr=1.50
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.4.4
  - r-lattice=0.22_7
  - r-lava=1.8.1
  - r-lazyeval=0.2.2
  - r-lhs=1.2.0
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-litedown=0.7
  - r-lme4=1.1_37
  - r-lmtest=0.9_40
  - r-lubridate=1.9.4
  - r-magrittr=2.0.3
  - r-markdown=2.0
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-matrixmodels=0.5_4
  - r-matrixstats=1.5.0
  - r-mclust=6.1.1
  - r-memoise=2.0.1
  - r-mgcv=1.9_3
  - r-microbenchmark=1.5.0
  - r-mime=0.13
  - r-miniui=0.1.2
  - r-minqa=1.2.8
  - r-modeldata=1.5.1
  - r-modelenv=0.2.0
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-munsell=0.5.1
  - r-nada=1.6_1.2
  - r-nlme=3.1_168
  - r-nloptr=2.2.1
  - r-nnet=7.3_20
  - r-numderiv=2016.8_1.1
  - r-openssl=2.3.3
  - r-padr=0.6.3
  - r-parallelly=1.45.1
  - r-parsnip=1.3.3
  - r-patchwork=1.3.2
  - r-pbkrtest=0.5.5
  - r-performanceanalytics=2.0.8
  - r-permute=0.9_8
  - r-pillar=1.11.0
  - r-pkgbuild=1.4.8
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.3
  - r-pkgload=1.4.0
  - r-plogr=0.2.0
  - r-plotly=4.11.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_7
  - r-polynom=1.4_1
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.19.0.1
  - r-processx=3.8.6
  - r-prodlim=2025.04.28
  - r-profvis=0.4.0
  - r-progress=1.2.3
  - r-progressr=0.15.1
  - r-promises=1.3.3
  - r-proxy=0.4_27
  - r-ps=1.9.1
  - r-purrr=1.1.0
  - r-quadprog=1.5_8
  - r-quantmod=0.4.28
  - r-quantreg=6.1
  - r-r.methodss3=1.8.2
  - r-r.oo=1.27.1
  - r-r.utils=2.13.0
  - r-r6=2.6.1
  - r-ragg=1.4.0
  - r-rappdirs=0.3.3
  - r-rbibutils=2.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.1.0
  - r-rcpparmadillo=14.6.3_1
  - r-rcppeigen=0.3.4.0.2
  - r-rcpproll=0.3.1
  - r-rdpack=2.6.4
  - r-reactable=0.4.4
  - r-reactr=0.6.1
  - r-readr=2.1.5
  - r-readxl=1.4.5
  - r-recipes=1.3.1
  - r-reformulas=0.4.1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-reprex=2.1.1
  - r-reshape2=1.4.4
  - r-rlang=1.1.6
  - r-rmarkdown=2.29
  - r-robustbase=0.99_4_1
  - r-roxygen2=7.3.2
  - r-rpart=4.1.24
  - r-rprojroot=2.1.1
  - r-rsample=1.3.1
  - r-rsqlite=2.4.3
  - r-rstatix=0.7.2
  - r-rstudioapi=0.17.1
  - r-rversions=2.1.2
  - r-rvest=1.0.5
  - r-sass=0.4.10
  - r-scales=1.4.0
  - r-scatterpie=0.2.5
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.3
  - r-sfd=0.1.0
  - r-shape=1.4.6.1
  - r-shiny=1.11.1
  - r-showtext=0.9_7
  - r-showtextdb=3.0
  - r-sitmo=2.0.2
  - r-slider=0.3.2
  - r-snakecase=0.11.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sparsem=1.84_2
  - r-sparsevctrs=0.3.4
  - r-squarem=2021.1
  - r-stringi=1.8.7
  - r-stringr=1.5.1
  - r-survival=3.8_3
  - r-svglite=2.2.1
  - r-sys=3.4.3
  - r-sysfonts=0.8.9
  - r-systemfonts=1.2.3
  - r-tailor=0.1.0
  - r-tensora=0.36.2.1
  - r-testthat=3.2.3
  - r-textshaping=1.0.1
  - r-tibble=3.3.0
  - r-tidymodels=1.4.1
  - r-tidyquant=1.0.9
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidytree=0.4.6
  - r-tidyverse=2.0.0
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-timeseries=4041.111
  - r-timetk=2.9.1
  - r-tinytex=0.57
  - r-truncnorm=1.0_9
  - r-tseries=0.10_58
  - r-tsfeatures=1.1.1
  - r-ttr=0.24.4
  - r-tune=2.0.0
  - r-tweenr=2.0.3
  - r-tzdb=0.5.0
  - r-urca=1.3_4
  - r-urlchecker=1.0.1
  - r-usethis=3.2.0
  - r-utf8=1.2.6
  - r-uuid=1.2_1
  - r-v8=6.0.6
  - r-vctrs=0.6.5
  - r-vegan=2.6_10
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.6.2
  - r-warp=0.2.1
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-workflows=1.3.0
  - r-workflowsets=1.1.1
  - r-writexl=1.5.4
  - r-xfun=0.53
  - r-xml2=1.4.0
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-xts=0.14.1
  - r-yaml=2.3.10
  - r-yardstick=1.3.2
  - r-yulab.utils=0.2.1
  - r-zcompositions=1.5.0_5
  - r-zip=2.3.3
  - r-zoo=1.8_14
  - readline=8.2
  - rpy2=3.6.2
  - scipy=1.16.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - sigtool=0.1.3
  - six=1.17.0
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tapi=1300.6.5
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomlkit=0.13.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xmltodict=0.15.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - rpy2-rinterface==3.6.2
      - rpy2-robjects==3.6.1
      - scikit-learn==1.5.0
      - stepmix==2.2.3
      - tqdm==4.67.1
