library(dplyr)
library(tidyLPA)
library(mclust)

set.seed(123)

config <- config::get()

# Import datafile generated by mplus
factor_scores <- read.table(paste0(config$data_processed, "comfort_factor_scores.dat"), header=FALSE) 

factor_scores <- factor_scores %>%
  dplyr::select('V43', 'V45', 'V47', 'V49', 'V51', 'V53', 'V55') %>%
  dplyr::rename(., c("Depression" = "V43", "Anxiety" = "V45", 
                     "Diarrhea" = "V47", "Constipation" = "V49", 
                     "Pain/bloating" = "V51", "Upper GI" = "V53", 
                     "Nausea and vomiting" = "V55"))

# Perform bootstrapping to calculate the optimal number of profiles
LRT <- mclustBootstrapLRT(factor_scores, nboot = 999, modelName = "EEI")

print(LRT)
